In [5]:
import numpy as np
mu_bar = np.array([[0],[0],[0],[4]])
G_t = np.eye(3)
mu_bar[:3] = np.array([
            [0],
            [1],
            [2]
        ])

print(mu_bar,np.shape(mu_bar))

[[0]
 [1]
 [2]
 [4]] (4, 1)


In [6]:
G_t[:3,:3] = np.array([
            [1 , 0  , -1],
            [0 , 1 , 1],
            [0 , 0, 1]
        ])
print(G_t)

[[ 1.  0. -1.]
 [ 0.  1.  1.]
 [ 0.  0.  1.]]
