In [ ]:
import numpy as np
mu_bar = np.zeros((3,1))
mu_bar[:3] = np.array([
            [0],
            [1],
            [2]
        ])

print(mu_bar,np.shape(mu_bar))

[[0]
 [1]
 [2]
 [4]] (4, 1)


In [ ]:
G_t = np.eye(3)
G_t[:3,:3] = np.array([
            [1 , 0  , -1],
            [0 , 1 , 1],
            [0 , 0, 1]
        ])
print(G_t)

[[ 1.  0. -1.]
 [ 0.  1.  1.]
 [ 0.  0.  1.]]


In [5]:
covariance_bar = np.array([[4, 2], [2, 3]])
k_gain = np.array([[0.5, 0.1], [0.2, 0.3]])
H_t_mat = np.array([[1, 0], [0, 1]])
Identity = np.eye(covariance_bar.shape[0])

final_covariance = np.dot((Identity - np.dot(k_gain, H_t_mat)), covariance_bar)
row, column = np.shape(final_covariance)

print("Final covariance matrix:")
print(final_covariance)
print("Rows:", row, "Columns:", column)


Final covariance matrix:
[[1.8 0.7]
 [0.6 1.7]]
Rows: 2 Columns: 2
