In [2]:
import numpy as np
mu_bar = np.zeros((4,1))
mu_bar[:3,:] = np.array([
            [0],
            [1],
            [2]
        ])

print(mu_bar,np.shape(mu_bar))

[[0.]
 [1.]
 [2.]
 [0.]] (4, 1)


In [3]:
G_t = np.eye(3)
G_t[:3,:3] = np.array([
            [1 , 0  , -1],
            [0 , 1 , 1],
            [0 , 0, 1]
        ])
print(G_t)

[[ 1.  0. -1.]
 [ 0.  1.  1.]
 [ 0.  0.  1.]]


In [4]:
covariance_bar = np.array([[4, 2], [2, 3]])
k_gain = np.array([[0.5, 0.1], [0.2, 0.3]])
H_t_mat = np.array([[1, 0], [0, 1]])
Identity = np.eye(covariance_bar.shape[0])
final_covariance = np.array([
    [1],
    [2],
    [3]
])
# final_covariance = np.dot((Identity - np.dot(k_gain, H_t_mat)), covariance_bar)
row, column = np.shape(final_covariance)

print("Final covariance matrix:")
print(final_covariance)
print(np.shape(final_covariance)[0])
print("Rows:", row, "Columns:", column)
print(final_covariance[2][0])


Final covariance matrix:
[[1]
 [2]
 [3]]
3
Rows: 3 Columns: 1
3


In [5]:
alpha = np.array([[0]*10,[0]*10])
print(alpha)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [6]:
alpha = np.zeros((3,1))
print(alpha)

[[0.]
 [0.]
 [0.]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])
d = np.array([[13,14],[15,16]])

e  = np.array([[a,b],[c,d]])
print(e)


[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [10]:
total_landmarks = 10
F_x = np.zeros((3,3+2*total_landmarks))
F_x[:3,:3] = np.eye(3,3)
print(F_x)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
